apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: ufu-asa-proj
  name: ufu-asa-proj
spec:
  replicas: 1  
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      io.kompose.service: ufu-asa-proj
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/projetomensageria-asa-bridge: "true"
        io.kompose.service: ufu-asa-proj
    spec:
      containers:
        - image: docker-ufu-asa-image
          name: ufu-asa-proj
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
              protocol: TCP
          resources:
            limits:
              cpu: "500m"  # Defines CPU limits for scaling
            requests:
              cpu: "250m"

      restartPolicy: Always
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ufu-asa-proj-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ufu-asa-proj
  minReplicas: 1
  maxReplicas: 10  # You can adjust the max replicas depending on your capacity
  targetCPUUtilizationPercentage: 50  # This is the threshold for scaling, set to 50% CPU utilization

